# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Comet Builder

on:
  push:
    branches: [ dev, stable ]
  pull_request:
    branches: [ dev, stable ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 设置 JDK 8 编译环境
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: 给予 gradlew 权限
        run: chmod +x gradlew
      - name: Gradle clean
        run: ./gradlew clean
      - name: Gradle shadowjar 打包
        run: ./gradlew shadowjar
      - uses: actions/upload-artifact@v2
        with:
          name: Nameless-Bot.jar
          path: build/libs
